# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

volumes:
  pgdata:
  walletstore:

services:
  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
      - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - ${ORDERER_ORG_PORT}:${ORDERER_ORG_PORT}

  peer0.org1Name.example.com:
    container_name: ${PEER0_ORG1_DOMAIN}
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=${PEER0_ORG1_DOMAIN}
      - CORE_PEER_ADDRESS=${PEER0_ORG1_CORE_ADDRESS} # define ip address
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${PEER0_ORG1_PORT}
      - CORE_PEER_CHAINCODEADDRESS=${PEER0_ORG1_CHAINCODE_ADDRESS} # define dns
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${PEER0_ORG1_CHAINCODE_PORT}
      - CORE_PEER_GOSSIP_BOOTSTRAP=${PEER1_ORG1_CORE_ADDRESS} ${PEER0_ORG2_CORE_ADDRESS} # define others ip address
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${PEER0_ORG1_CORE_ADDRESS} # define ip address
      - CORE_PEER_LOCALMSPID=${ORG1_MSPNAME} # define msp name
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/${ORG1_DOMAIN}/peers/${PEER0_ORG1_DOMAIN}/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/${ORG1_DOMAIN}/peers/${PEER0_ORG1_DOMAIN}/tls:/etc/hyperledger/fabric/tls
      - ${PEER0_ORG1_DOMAIN}:/var/hyperledger/production
    ports:
      - ${PEER0_ORG1_PORT}:${PEER0_ORG1_PORT}

  peer1.org1Name.example.com:
    container_name: ${PEER1_ORG1_DOMAIN}
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=${PEER1_ORG1_DOMAIN}
      - CORE_PEER_ADDRESS=${PEER1_ORG1_CORE_ADDRESS} # define ip address
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${PEER1_ORG1_PORT}
      - CORE_PEER_CHAINCODEADDRESS=${PEER1_ORG1_CHAINCODE_ADDRESS} # define dns
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${PEER1_ORG1_CHAINCODE_PORT}
      - CORE_PEER_GOSSIP_BOOTSTRAP=${PEER0_ORG1_CORE_ADDRESS} ${PEER0_ORG2_CORE_ADDRESS} # define others ip address
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${PEER1_ORG1_CORE_ADDRESS} # define ip address
      - CORE_PEER_LOCALMSPID=${ORG1_MSPNAME} # define msp name
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/${ORG1_DOMAIN}/peers/${PEER1_ORG1_DOMAIN}/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/${ORG2_DOMAIN}/peers/${PEER1_ORG1_DOMAIN}/tls:/etc/hyperledger/fabric/tls
      - ${PEER1_ORG1_DOMAIN}:/var/hyperledger/production
    ports:
      - ${PEER1_ORG1_PORT}:${PEER1_ORG1_PORT}

  peer0.org2Name.example.com:
    container_name: ${PEER0_ORG2_DOMAIN}
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=${PEER0_ORG2_DOMAIN}
      - CORE_PEER_ADDRESS=${PEER0_ORG2_CORE_ADDRESS} # define ip address
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${PEER0_ORG2_PORT}
      - CORE_PEER_CHAINCODEADDRESS=${PEER0_ORG2_CHAINCODE_ADDRESS} # define dns
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${PEER0_ORG2_CHAINCODE_PORT}
      - CORE_PEER_GOSSIP_BOOTSTRAP=${PEER0_ORG1_CORE_ADDRESS} ${PEER1_ORG1_CORE_ADDRESS} # define others ip address
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${PEER0_ORG2_CORE_ADDRESS} # define ip address
      - CORE_PEER_LOCALMSPID=${ORG2_MSPNAME} # define msp name
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/${ORG2_DOMAIN}/peers/${PEER0_ORG2_DOMAIN}/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/${ORG2_DOMAIN}/peers/${PEER0_ORG2_DOMAIN}/tls:/etc/hyperledger/fabric/tls
      - ${PEER0_ORG2_DOMAIN}:/var/hyperledger/production
    ports:
      - ${PEER0_ORG2_PORT}:${PEER0_ORG2_PORT}
